### ISSUE TITLE
Normalize headers

### ISSUE THREAD

**Issue by MBach** [deezer/native-sdk-samples#1]
Hi @CPicheney 
I've started to read the headers found [here](http://cdn-files.deezer.com/developers/deezer-native-sdk-v1.0.0.2-v00348791.zip) in order to migrate my [plugin](https://github.com/MBach/deezer-plugin) from JavaScript SDK to Native SDK. 
IMHO, you shouldn't mix tabs and spaces for indentation.
Regards,

**Comment by CPicheney** [comment]
Hello @MBach ,
You are totally right. It will be fixed in the next release.
Thank you for your feedback.
Cyril

**Comment by CPicheney** [comment]
Hello @MBach ,
It should be fixed now.
Thank you for your feedback.
Best regards,
Cyril
