### ISSUE TITLE
PythonSample doesn't work on Raspbery Pi 3 with Raspbian

### ISSUE THREAD

**Issue by ctotof38** [deezer/native-sdk-samples#14]
I use this simple command, with default value : app_start.py dzmedia:///playlist/1363560485

On standard ubuntu 16.04 64 bits kernel 4.4.0 with python 2.7.12  :
------------------------------------------------------------------------------------
29414:132595 dz_crash_handler: [dz_crash_handler_init:284] Crash Handler available
(u'Device ID:', 'd19335f59e838cf8f87e5a4108c56e88')
29414:135274 pulseaudio-engine: [dz_audioengine_set_output_gain:1229] not init
29414:135279 pulseaudio-engine: [dz_audioengine_set_output_gain:1229] not init
---- Deezer NativeSDK version: 1.1.1_20161018-094633-efa08cf6
---- Application ID: 190262
---- Product ID: PythonSampleApp
LOAD =>
...
29414:146264 connect-session: [dz_connect_session_offline_mode:1709] offline_mode_forced:0 online_state:0 tok:1 m:0
29414:146276 connect-session: [dz_connect_set_session_state:1414] 0
29414:150842 connect-session: [dz_connect_on_cache_userme:1886] ret:0
29414:150848 connect-session: [dz_connect_offline_update_data_state:1948] state:0 offline_state:0
29414:150853 connect-session: [dz_connect_on_cache_userlicense:1921] ret:0
29414:150858 connect-session: [dz_connect_offline_update_data_state:1948] state:0 offline_state:0
29414:150864 connect-session: [dz_connect_set_session_state:1414] 2
++++ CONNECT_EVENT ++++ USER_OFFLINE_AVAILABLE
29414:435440 connect-session: [dz_connect_session_user_info_cb:948] api_ret:1 responsedata:0x7f146c065930
++++ CONNECT_EVENT ++++ USER_LOGIN_OK
----> LOAD dzmedia:///playlist/1363560485
29414:435939 connect-session: [dz_connect_set_session_state:1414] 3
29414:435949 connect-log: [dz_connectlog_stream_player_event_notify_technical:914] Event type = LOGIN
29414:438517 array: [dz_array_get_obj:95] error, return value: 0x0
==== PLAYER_EVENT ==== QUEUELIST_LOADED
index: 0
==== PLAYER_EVENT ==== QUEUELIST_TRACK_SELECTED - is_preview: 0
    can_pause_unpause: True - can_seek: True
... 
And the music start

The same command on Raspbian kernel 4.4.50 with python 2.7.9 :
------------------------------------------------------------------------------------
8743:560395 dz_crash_handler: [dz_crash_handler_init:286] Crash Handler available
(u'Device ID:', '0b6ad07556f9e64f241c5b5f3ea331e2')
8743:571059 pulseaudio-engine: [dz_audioengine_set_output_gain:1229] not init
8743:571095 pulseaudio-engine: [dz_audioengine_set_output_gain:1229] not init
---- Deezer NativeSDK version: 1.2.0_20170307-174734-b23acba9
---- Application ID: 190262
---- Product ID: PythonSampleApp
LOAD => 
...
8743:576350 connect-session: [dz_connect_session_offline_mode:1709] offline_mode_forced:0 online_state:0 tok:1 m:0
8743:576783 connect-session: [dz_connect_set_session_state:1414] 0
8743:598056 connect-session: [dz_connect_on_cache_userme:1886] ret:0
8743:598395 connect-session: [dz_connect_offline_update_data_state:1948] state:0 offline_state:0
8743:598587 connect-session: [dz_connect_on_cache_userlicense:1921] ret:0
8743:598770 connect-session: [dz_connect_offline_update_data_state:1948] state:0 offline_state:0
8743:598951 connect-session: [dz_connect_set_session_state:1414] 2
++++ CONNECT_EVENT ++++ USER_OFFLINE_AVAILABLE
8743:879079 connect-session: [dz_connect_session_user_info_cb:948] api_ret:1 responsedata:0x729524e8
++++ CONNECT_EVENT ++++ USER_LOGIN_OK
----> LOAD dzmedia:///playlist/1363560485
8743:882501 connect-session: [dz_connect_set_session_state:1414] 3
8743:882748 connect-log: [dz_connectlog_stream_player_event_notify_technical:914] Event type = LOGIN
8743:890692 resourcecache: [dz_resourcecache_inodedata_set_reserve_complete_space:1775] size changed, should not happen
8743:894461 resourcecache: [dz_resourcecache_inodedata_set_reserve_complete_space:1775] size changed, should not happen
==== PLAYER_EVENT ==== QUEUELIST_LOADED
index: 0
8744:765879 array: [dz_array_get_obj:96] error, return value: 0x0
8744:766182 connect-licensetrackstore: [dz_licensetrackstore_check_rights:250] error, return value: 0x72955138
==== PLAYER_EVENT ==== QUEUELIST_TRACK_NO_RIGHT

what's appear ? is it the error licensetrackstore ?

Thanks

Regards

Christophe

**Comment by ctotof38** [comment]
Hello,
if fact, among the example provide with this example, (track, album, playlist, radio-220...) there is one which is working good :
    app_start.py dzmedia://track/10257076

Very strange behavior ! On my Linux Ubuntu, all examples are working perfectly...

**Comment by ctotof38** [comment]
Another clarification : with NanoPlayer, all is working on both plateforms. With the same SDK...

**Comment by CPicheney** [comment]
Hello Christophe,

Thank you very much for you detailed feedback.
I will try to reproduce your issue and come back to you ASAP.

Best regards,

Cyril

**Comment by CPicheney** [comment]
I can reproduce the issue, no idea why it occurs.

**Comment by CPicheney** [comment]
Hello Christophe,

The issue was in the python wrapper.
I have fixed it.
Please get the last commit 5e2931a and let me know.
Many thanks for your feedback.

Cyril

**Comment by ctotof38** [comment]
Hello Cyril,
it's fantastic, I can launch an album or a playlist on Raspberry Pi :o)
But I have another little problem...

When I want to go to next or previous track, I have to do STOP / START to hear my music. Only on Raspberry Pi, not on my Ubuntu 64 bits desktop.

Here is the log on my Ubuntu, I start the album, then I go to next (+) and previous (-)
---------------------------------------------------------------------------------------
app_start.py dzmedia:///playlist/1363560485
---- Deezer NativeSDK version: 1.2.0_20170307-173920-b23acba9
---- Application ID: 190262
---- Product ID: PythonSampleApp
==== PLAYER_EVENT ==== QUEUELIST_LOADED
index: 0
==== PLAYER_EVENT ==== QUEUELIST_TRACK_SELECTED - is_preview: 0
	can_pause_unpause: True - can_seek: True
==== PLAYER_EVENT ==== MEDIASTREAM_DATA_READY
==== PLAYER_EVENT ==== RENDER_TRACK_START
+
NEXT => dzmedia:///playlist/1363560485
==== PLAYER_EVENT ==== RENDER_TRACK_REMOVED
==== PLAYER_EVENT ==== QUEUELIST_TRACK_SELECTED - is_preview: 0
	can_pause_unpause: True - can_seek: True
	now:{...}
==== PLAYER_EVENT ==== MEDIASTREAM_DATA_READY
==== PLAYER_EVENT ==== RENDER_TRACK_START
-
PREVIOUS => dzmedia:///playlist/1363560485
==== PLAYER_EVENT ==== RENDER_TRACK_REMOVED
==== PLAYER_EVENT ==== QUEUELIST_TRACK_SELECTED - is_preview: 0
	can_pause_unpause: True - can_seek: True
	now:{...}
==== PLAYER_EVENT ==== MEDIASTREAM_DATA_READY
==== PLAYER_EVENT ==== RENDER_TRACK_START
Q
---------------------------------------------------------------------------------------

And the log on my Raspberry Pi to have the same behavior
---------------------------------------------------------------------------------------
app_start.py dzmedia:///playlist/1363560485
---- Deezer NativeSDK version: 1.2.0_20170307-174734-b23acba9
---- Application ID: 190262
---- Product ID: PythonSampleApp
==== PLAYER_EVENT ==== QUEUELIST_LOADED
index: 0
==== PLAYER_EVENT ==== QUEUELIST_TRACK_SELECTED - is_preview: 0
	can_pause_unpause: True - can_seek: True
	now:{...}
==== PLAYER_EVENT ==== MEDIASTREAM_DATA_READY
==== PLAYER_EVENT ==== RENDER_TRACK_START
+
NEXT => dzmedia:///playlist/1363560485
==== PLAYER_EVENT ==== RENDER_TRACK_REMOVED
==== PLAYER_EVENT ==== QUEUELIST_TRACK_SELECTED - is_preview: 0
	can_pause_unpause: True - can_seek: True
	now:{...}
==== PLAYER_EVENT ==== MEDIASTREAM_DATA_READY
==== PLAYER_EVENT ==== RENDER_TRACK_START
S
STOP => dzmedia:///playlist/1363560485
==== PLAYER_EVENT ==== RENDER_TRACK_REMOVED
S
PLAY => dzmedia:///playlist/1363560485
==== PLAYER_EVENT ==== QUEUELIST_TRACK_SELECTED - is_preview: 0
	can_pause_unpause: True - can_seek: True
	now:{...}
==== PLAYER_EVENT ==== MEDIASTREAM_DATA_READY
==== PLAYER_EVENT ==== RENDER_TRACK_START
---------------------------------------------------------------------------------------

I can see one difference : 
- on Ubuntu : 1.2.0_20170307-173920-b23acba9
- on Raspberry : 1.2.0_20170307-174734-b23acba9

I use the same lastest SDK archive... Perhaps it's normal to have a different value ?

And the second remark is that this example use 100% CPU. On my desktop, it's not really a problem, because I have several CPU cores, but on the Raspberry Pi 3, it is probably more important. Perhaps that's why it can't start music after change the track...

Regards

Christophe

**Comment by ctotof38** [comment]
And sorry for the big character, I don't know why it's appear !

**Comment by CPicheney** [comment]
Hello Christophe,

Thank you again for your feedback.

Could you test it again?

It was definitely over consuming CPU.
It should be fine now and have the same behavior than your Ubuntu.
It was the case on my side.

Best regards :)

Cyril

**Comment by ctotof38** [comment]
I found a solution to my problem. The previous test was done with the native sound card. I add an USB card, configure the file ~/.asoundrc to use my card Nb 1

```
pcm.!default {
 	type hw
 	card 1
}
 
ctl.!default {
 	type hw
 	card 1
}

``` 

reboot my Raspberry Pi, and launch the program. I can change track of my playlist and it works like on my Ubuntu...

for information
```
lsusb
Bus 001 Device 004: ID 0d8c:0014 C-Media Electronics, Inc. 

```

```
aplay -l
...
carte 1: Device [USB Audio Device], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0

```

Regards

Christophe
