### ISSUE TITLE
Entity: line 1: parser error : Document is empty

### ISSUE THREAD

**Issue by sheregeda** [deezer/native-sdk-samples#15]
Hello!
I have error messages when starting script app_start.py with debug_mode=False: 

3992970:513172 dz_crash_handler: [dz_crash_handler_init:286] Crash Handler available
Entity: line 1: parser error : Document is empty
sas_noad = true;
^

What does it mean? How to fix it?

**Comment by CPicheney** [comment]
Hello Sheregeda,

Thank you for your message.

Unfortunately I can not reproduce the issue. It seems this issue is linked to your system configuration.
Do you use an ad blocker ?

From which country are you trying to use this sample?

Do you use the default USER_ACCESS_TOKEN provided in the sample or a different one?

Could you send me the full traces?

Best regards,

Cyril

**Comment by sheregeda** [comment]
Hi!
Sorry for my incomplete question.

>>Do you use an ad blocker ?

No, I use the Native SDK in python script and run in the linux terminal.


>>It seems this issue is linked to your system configuration.

My system configuration: 
Linux desktop 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 15.10


>>From which country are you trying to use this sample?

From Russia.


>>Do you use the default USER_ACCESS_TOKEN provided in the sample or a different one?

When I use the default USER_ACCESS_TOKEN provided in the sample I have errors:
3992970:513172 dz_crash_handler: [dz_crash_handler_init:286] Crash Handler available
Entity: line 1: parser error : Document is empty
sas_noad = true;
^

When I set another access token I have error in debug mode off:
3992970:513172 dz_crash_handler: [dz_crash_handler_init:286] Crash Handler available


>>Could you send me the full traces?

$ python app_start.py dzmedia:///track/10287076

4161567:638495 dz_crash_handler: [dz_crash_handler_init:286] Crash Handler available
Device ID: b'843aff2d43a0117356391b09103492a6'
4161567:666424 pulseaudio-engine: [dz_audioengine_set_output_gain:1229] not init
4161567:666449 pulseaudio-engine: [dz_audioengine_set_output_gain:1229] not init
---- Deezer NativeSDK version: b'1.2.0_20170307-173920-b23acba9'
---- Application ID: 190262
---- Product ID: PythonSampleApp
LOAD => 
4161567:673803 connect-session: [dz_connect_session_offline_mode:1709] offline_mode_forced:0 online_state:0 tok:1 m:0
4161567:673827 connect-session: [dz_connect_set_session_state:1414] 0
4161567:677244 connect-session: [dz_connect_on_cache_userme:1886] ret:0
4161567:677263 connect-session: [dz_connect_offline_update_data_state:1948] state:0 offline_state:0
4161567:677273 connect-session: [dz_connect_on_cache_userlicense:1921] ret:0
4161567:677287 connect-session: [dz_connect_offline_update_data_state:1948] state:0 offline_state:0
4161567:677295 connect-session: [dz_connect_set_session_state:1414] 2
++++ CONNECT_EVENT ++++ USER_OFFLINE_AVAILABLE
4161568:015144 connect-session: [dz_connect_session_user_info_cb:948] api_ret:1 responsedata:0x7feae40678b0
++++ CONNECT_EVENT ++++ USER_LOGIN_OK
----> LOAD dzmedia:///track/10287076
4161568:015570 connect-session: [dz_connect_set_session_state:1414] 3
4161568:015584 connect-log: [dz_connectlog_stream_player_event_notify_technical:914] Event type = LOGIN
==== PLAYER_EVENT ==== QUEUELIST_LOADED
index: 0
==== PLAYER_EVENT ==== QUEUELIST_TRACK_SELECTED - is_preview: 0
	can_pause_unpause: True - can_seek: True
	now:b'{"id":10287076,"readable":true,"title":"Walk","title_short":"Walk","title_version":"","isrc":"USRW31100002","link":"https:\\/\\/www.deezer.com\\/track\\/10287076","share":"http:\\/\\/www.deezer.com\\/track\\/10287076?utm_source=deezer&utm_content=track-10287076&utm_term=980049722_1496327026&utm_medium=linux","duration":256,"track_position":11,"disk_number":1,"rank":663924,"release_date":"2011-04-08","explicit_lyrics":false,"bpm":140.100000,"gain":-6.600000,"contributors":[{"id":566,"name":"Foo Fighters","link":"https:\\/\\/www.deezer.com\\/artist\\/566","share":"http:\\/\\/www.deezer.com\\/artist\\/566?utm_source=deezer&utm_content=artist-566&utm_term=980049722_1496327026&utm_medium=linux","picture":"https:\\/\\/api.deezer.com\\/artist\\/566\\/image","picture_small":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/56x56-000000-80-0-0.jpg","picture_medium":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/250x250-000000-80-0-0.jpg","picture_big":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/500x500-000000-80-0-0.jpg","picture_xl":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/1000x1000-000000-80-0-0.jpg","radio":true,"tracklist":"https:\\/\\/api.deezer.com\\/artist\\/566\\/top?limit=50","type":"artist","role":"Main"},{"id":566,"name":"Foo Fighters","link":"https:\\/\\/www.deezer.com\\/artist\\/566","share":"http:\\/\\/www.deezer.com\\/artist\\/566?utm_source=deezer&utm_content=artist-566&utm_term=980049722_1496327026&utm_medium=linux","picture":"https:\\/\\/api.deezer.com\\/artist\\/566\\/image","picture_small":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/56x56-000000-80-0-0.jpg","picture_medium":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/250x250-000000-80-0-0.jpg","picture_big":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/500x500-000000-80-0-0.jpg","picture_xl":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/1000x1000-000000-80-0-0.jpg","radio":true,"tracklist":"https:\\/\\/api.deezer.com\\/artist\\/566\\/top?limit=50","type":"artist","role":"Featured"}],"artist":{"id":566,"name":"Foo Fighters","link":"https:\\/\\/www.deezer.com\\/artist\\/566","share":"http:\\/\\/www.deezer.com\\/artist\\/566?utm_source=deezer&utm_content=artist-566&utm_term=980049722_1496327026&utm_medium=linux","picture":"https:\\/\\/api.deezer.com\\/artist\\/566\\/image","picture_small":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/56x56-000000-80-0-0.jpg","picture_medium":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/250x250-000000-80-0-0.jpg","picture_big":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/500x500-000000-80-0-0.jpg","picture_xl":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/artist\\/72de144104cc2b92282bf0c805301816\\/1000x1000-000000-80-0-0.jpg","radio":true,"tracklist":"https:\\/\\/api.deezer.com\\/artist\\/566\\/top?limit=50","type":"artist"},"album":{"id":940640,"title":"Wasting Light","link":"https:\\/\\/www.deezer.com\\/album\\/940640","cover":"https:\\/\\/api.deezer.com\\/album\\/940640\\/image","cover_small":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/cover\\/0fe7001d870aee7b3376a8f523bd820e\\/56x56-000000-80-0-0.jpg","cover_medium":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/cover\\/0fe7001d870aee7b3376a8f523bd820e\\/250x250-000000-80-0-0.jpg","cover_big":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/cover\\/0fe7001d870aee7b3376a8f523bd820e\\/500x500-000000-80-0-0.jpg","cover_xl":"https:\\/\\/e-cdns-images.dzcdn.net\\/images\\/cover\\/0fe7001d870aee7b3376a8f523bd820e\\/1000x1000-000000-80-0-0.jpg","release_date":"2011-04-08","tracklist":"https:\\/\\/api.deezer.com\\/album\\/940640\\/tracks","type":"album"},"type":"track"}'
==== PLAYER_EVENT ==== MEDIASTREAM_DATA_READY
==== PLAYER_EVENT ==== RENDER_TRACK_START
Entity: line 1: parser error : Document is empty
sas_noad = true;
^
4161568:295764 ads-vast: [dz_connect_ads_audioads_requestdone_cb:358] error parsing xml data consumed:0
4161568:295779 ads: [dz_adsengine_on_audioads_fetch:159] failed to load ads err:b

**Comment by CPicheney** [comment]
Hello,

I am sorry to announce that the Deezer Native SDK is no more available and supported.

This project is not maintained and is now closed.

We don't have any other alternative to propose than those already available here: https://developers.deezer.com/

I am very sorry for the inconvenience.

Best regards,

Cyril
