### ISSUE TITLE
c# wrapper

### ISSUE THREAD

**Issue by ericleroy01** [deezer/native-sdk-samples#17]
Bonjour,

J'ai intégré le fichier DZConnection.cs dans un projet uwp créé avec VS2017.

si je fais appel à la méthode dz_connect_new j'obitens le message d'erreur 
System.TypeLoadException: Cannot marshal field 'anonymous_blob' of type 'dz_connect_configuration': Invalid managed/unmanaged type combination (Int/UInt must be paired with SysInt or SysUInt).
at System.StubHelpers.ValueClassMarshaler.ConvertToNative(IntPtr dst, IntPtr src, IntPtr pMT, CleanupWorkList& pCleanupWorkList)
   at DZConnection.dz_connect_new(dz_connect_configuration& config)
  at DZConnection..ctor(dz_connect_configuration config)
   at Deezer.Pages.Login.PlaySong(String token)"

après modification de la structure dz_connect_configuration
public IntPtr anonymous_blob => public string anonymous_blob

le messsage disparait mais la méthode dz_connect_new retourne toujours un handle à zéro.

quel est le problème ?

NB : j'utilise la dernirèe version du ssk disponible sur le site developers.deezer.com

**Comment by CPicheney** [comment]
Bonjour,

Merci pour votre retour, effectivement c'est un bon point.

Pourriez-vous me partager votre projet d'exemple complet?

C'est étrange, la seule raison pour laquelle dz_connect_new retournerait un handle null serait de lui passer un pointeur de configuration null....

Bien cordialement,

Cyril

**Comment by ericleroy01** [comment]
private void PlaySong(String token)
        {
//le token est récupéré via les api
            try
            {
                dz_connect_configuration config = new dz_connect_configuration();
                config.app_id = "00000"; //appid récuperé sur l'écran de gestion des apps
                config.product_id = "appname"; //application name associé à l'appid
                config.product_build_id = "0001";
                config.user_profile_path = "C:\\Development\\Deezer\\";
                //config.connect_event_cb = ConnectionOnEventCallback; //optional
                //config.anonymous_blob = string.Empty; //optional
                
                DZConnection dzConnection = new DZConnection(config);
                dzConnection.SetAccessToken(token);
                dzConnection.SetOfflineMode(false);
                dzConnection.Activate(new IntPtr(this.GetHashCode()));

                DZPlayer dzPlayer = new DZPlayer(dzConnection.Handle);
                dzPlayer.Load("dzmedia:///track/3135556");
                dzPlayer.Play();

            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

**Comment by filipkristo** [comment]
@ericleroy01 you can take a look pull request #19.

**Comment by CPicheney** [comment]
Hello,

I am sorry to announce that the Deezer Native SDK is no more available and supported.

This project is not maintained and is now closed.

We don't have any other alternative to propose than those already available here: https://developers.deezer.com/

I am very sorry for the inconvenience.

Best regards,

Cyril
