### ISSUE TITLE
some headers are missing cpp support in native SDK

### ISSUE THREAD

**Issue by IRebo** [deezer/native-sdk-samples#2]
Hi,

i noticed some headers in the native SDK are missing the cpp extern definition so creating something in cpp that uses the player doesnt work. Adding these to the rest of the headers fixes the problem.

#ifdef __cplusplus
extern "C" {
#endif

Ivan

**Comment by CPicheney** [comment]
Hello @IRebo ,
You are totally right. It will be fixed in the next release.
Thank you for your feedback.
Best regards,
Cyril

**Comment by CPicheney** [comment]
Hello @IRebo ,
It should be fixed now.
Thank you for your feedback.
Best regards,
Cyril
