### ISSUE TITLE
No callback on “dz_player_pause” with Linux Native SDK

### ISSUE THREAD

**Issue by blackccpie** [deezer/native-sdk-samples#20]
Hi,

I'm facing the exact same issue described in the following stackoverflow topic:

[deezer-native-sdk-arm-no-callback-on-dz-player-pause-bug](https://stackoverflow.com/questions/42043593/deezer-native-sdk-arm-no-callback-on-dz-player-pause-bug)

I'm using the SDK v1.2.10, which does not seem to include this bug fix, can you confirm?

Thx

**Comment by jazzycamel** [comment]
Hi,

I'm facing the same bug (no pause event) on Linux (x86_64) using SDK version 1.2.10_20170727-164521-63a1132a

Cheers

**Comment by blackccpie** [comment]
Hi @jazzycamel, I wrote to the deeper support team, and they confirmed the bug. But they don't known when this will be fixed :-(

Cheers

**Comment by CPicheney** [comment]
Hello,

I am sorry to announce that the Deezer Native SDK is no more available and supported.

This project is not maintained and is now closed.

We don't have any other alternative to propose than those already available here: https://developers.deezer.com/

I am very sorry for the inconvenience.

Best regards,

Cyril
