### ISSUE TITLE
libssl1.0.0 is required

### ISSUE THREAD

**Issue by MFAshby** [deezer/native-sdk-samples#23]
Building the sample NanoPlayer application on a modern linux distribution (e.g. debian 9, or latest ubuntu, or raspbian) fails, with the following error:
`***********  Linux  ************
***********  64 Bits  ************
gcc -o main.o -c main.c -W -Wall -I../NativeSDK/Include -Wno-unused-parameter
gcc -o NanoPlayer main.o -L../NativeSDK/Bins/Platforms/Linux/x86_64 -Wl,-rpath ../NativeSDK/Bins/Platforms/Linux/x86_64 -ldeezer
/usr/bin/ld: warning: libssl.so.1.0.0, needed by ../NativeSDK/Bins/Platforms/Linux/x86_64/libdeezer.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by ../NativeSDK/Bins/Platforms/Linux/x86_64/libdeezer.so, not found (try using -rpath or -rpath-link)
../NativeSDK/Bins/Platforms/Linux/x86_64/libdeezer.so: undefined reference to X509_verify_cert@OPENSSL_1.0.0`

Running the python sample also fails due to library load error.

This is most likely due to the Deezer library being linked to libssl1.0.0. Could an updated version linked to a more modern SSL implementation be released? This old library is no longer available in many linux distributions.

**Comment by CPicheney** [comment]
Hello,

I am sorry to announce that the Deezer Native SDK is no more available and supported.

This project is not maintained and is now closed.

We don't have any other alternative to propose than those already available here: https://developers.deezer.com/

I am very sorry for the inconvenience.

Best regards,

Cyril
