### ISSUE TITLE
No more native SDK

### ISSUE THREAD

**Issue by wibimaster** [deezer/native-sdk-samples#25]
Where is the native SDK now ? All links are broken, repository too :/

**Comment by MFAshby** [comment]
I've got a fork [here](https://github.com/MFAshby/native-sdk-samples) which has the native SDK headers & binaries. 
I guess it will stop working soon though if Deezer are deprecating the native SDK.

**Comment by wibimaster** [comment]
My bad, company's firewall blocked the link.....
