### ISSUE TITLE
Linking problems: CURL_OPENSSL_3

### ISSUE THREAD

**Issue by jonaski** [deezer/native-sdk-samples#26]
Any idea how to solve this:

```
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_getdate@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_multi_cleanup@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_multi_add_handle@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_easy_init@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_multi_setopt@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_multi_assign@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_multi_remove_handle@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_multi_socket_action@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_easy_pause@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_easy_send@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_slist_free_all@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_slist_append@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_multi_init@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_share_setopt@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_share_init@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_share_cleanup@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_multi_info_read@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_global_init@CURL_OPENSSL_3'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libdeezer.so: undefined reference to `curl_easy_recv@CURL_OPENSSL_3'

```

**Comment by KottV** [comment]
Hi.

I found your very nice strawberry player :) and struggle with same issue in openSUSE TW.
I think they built SDK on Debian Stretch (or Ubuntu) with old curl-openssl libs. Maybe there is some way to build custom curl and preload it (if it worth at all), but I didn't try yet.

**Comment by jonaski** [comment]
Apparently they've built the library using a ubuntu distro, and debian/ubuntu uses special symbols, so it's incompatible with all other linux distros, and also incompatible with the latest versions of ubuntu since they changed their packages, they don't provide libcurl packed with those symbols anymore.
I did some attempts to compile libcurl with changed symbols, but I gave up. If we are able to compile it with the same symbols, I think it should be possible to include it in 3rdparty and statically link to it and that way it might work. However it was too much hassle to figure it out, if you want to try that's great.
I've used Ubuntu 16.4 in a virtualbox to implement the engine and test it, it also works on Windows without any linking issues.

When I saw that Deezer had started offering FLAC and also offered a open API, this was exactly what I was looking for.
Before I started implementing the Deezer support I read their API documentation thoughtfully. Their API advertising says "Unlimited Access". I also emailed them, I even sent them a link to the repository on GitHub. They didn't tell me this. And apparently I didn't read their other page (Guidelines) thoughtfully, or maybe I did not grasp that they actually have an API thats pretty useless for what they sell. I did not understand that they did not provide full length stream through their API other than web flash. I only found this out when I didn't find the urls through the API.
They are not responding to my e-mails now.
I don't know if they have discontinued their SDK for linux. There is no clear information.
Maybe they did, and did it for this reason.

**Comment by KottV** [comment]
Thank You for detailed answer.
I'm not sure that such efforts can be successful. I mean dancing with symbols and static linking.
Maybe building AppImage or so on Ubuntu 16.04 may give chance for other distros.

Regarding Dezzer's policy I haven't to say anything.

**Comment by CPicheney** [comment]
Hello,

I am sorry to announce that the Deezer Native SDK is no more available and supported.

This project is not maintained and is now closed.

We don't have any other alternative to propose than those already available here: https://developers.deezer.com/

I am very sorry for the inconvenience.

Best regards,

Cyril
