### ISSUE TITLE
starting the player in online mode requires undocumented call

### ISSUE THREAD

**Issue by IRebo** [deezer/native-sdk-samples#3]
Hi,

i noticed that to get the native SDK to play online file you need to call
dz_connect_offline_mode with force_offline as false. This seems to start the background login process. If this intentional and shouldnt there rather be some kind of a dz_connect_login() function instead ?

Also it would be useful to mention this on http://developers.deezer.com/sdk/native as there are no samples for the SDK currently available and its hard to figure it out. (see http://stackoverflow.com/questions/37229812/c-sharp-wrapper-for-c-deezer-library-playlist-track-no-right/37254570#37254570)

Ivan

**Comment by CPicheney** [comment]
Hello IRebo,
Thank you for your feedback, you are totally right.
I am currently working on a basic sample code in C and I will add this point on the documentation.
Many thanks.
Cyril

**Comment by IRebo** [comment]
thank you !

**Comment by CPicheney** [comment]
Hello,

I am sorry to announce that the Deezer Native SDK is no more available and supported.

This project is not maintained and is now closed.

We don't have any other alternative to propose than those already available here: https://developers.deezer.com/

I am very sorry for the inconvenience.

Best regards,

Cyril
