### ISSUE TITLE
GCC ABI problem

### ISSUE THREAD

**Issue by JedS** [deezer/native-sdk-samples#6]
Hi,
I try to compile this code on i386 linux system ( xbuntu).
I got a linker error about undefined reference for libdeezer.so to symbol :

- std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@@GLIBCXX_3.4.21
- std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@@GLIBCXX_3.4.21
- std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@@GLIBCXX_3.4.21

I try to compile this code with GCC 4.9, GCC 5.3.0 and GCC 6.1 , without any success.

As far as I understand, it seems your lib has been compiled with the new ABI ( https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html ) and my libstdc++ isn't.

Is there any chance you release the libdeezer.so compiled using an old ABI ?

Regards,

JedS

**Comment by CPicheney** [comment]
Hello JedS,

I should be fixed with the last version of the Native SDK 1.0.2 (Released 3rd June).
Could you please confirm?

Best regards, 

Cyril

**Comment by JedS** [comment]
Hi,

I just upgrade my Linux version to Ubuntu 16.04 LTS, using GCC 5.3.1 
which support both new and old ABI.

But running :

/readelf -Ws libdeezer.so | c++filt
/

doesn't show anymore the cxx11 symbol. So, I guess the latest version 
should fix the bug.

Is it possible to make any request for your SDK evolution ?

Best Regards

JedS

PS : Are you french ?


Le 29/06/2016 à 10:49, CPicheney a écrit :
>
> Hello JedS,
>
> I should be fixed with the last version of the Native SDK 1.0.2 
> (Released 3rd June).
> Could you please confirm?
>
> Best regards,
>
> Cyril
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/deezer/native-sdk-samples/issues/6#issuecomment-229295794>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ATEjz3PyDFcYU1F8GbwJWg0tvHq__2BMks5qQjGfgaJpZM4I4fjv>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
